{
    'name': 'TAP Fleet',
    'author' : 'TAP',
    'version': '15.0.0.1',
    'website': 'https://www.technischeausbaupartnergmbh.de/',
    'category': 'TAP/Fleet',
    'license': 'LGPL-3',
    'summary': 'Manage your fleet and track car costs',
    'description': '',
    'depends': [
        'fleet'
    ],
    'data': [
        'views/next_increment_number_views.xml',
        'views/repair_type_views.xml',
        'views/next_service_days_views.xml',
        'views/fleet_service_views.xml',
        'views/fleet_breakdown_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/fleet_vehicle_cost_views.xml',
        'views/update_pending_repair_history_views.xml',
        'views/pending_repair_type_views.xml',
        'wizards/update_history_views.xml',
        'wizards/continue_pending_repair_views.xml',
        'wizards/pending_repair_confirm_views.xml',
        'wizards/update_next_service_views.xml',
        'wizards/breakdown_cancel_reason_views.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/repair_type_data.xml',
        'data/vehicle_type_data.xml',
        'data/color_color_data.xml',
        'data/damage_type_data.xml',
        'data/scheduler_data.xml',
        'views/menuitems_views.xml',
        'reports/reports.xml',
        'reports/report_breakdown_qweb.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}