from . import fleet_configuration
from . import fleet_vehicle
from . import fleet_vehicle_log_contract
from . import fleet_service
from . import service_repair_line
from . import fleet_history
from . import pending_repair_type
from . import update_pending_repair_history
from . import fleet_breakdown
from . import repair_type_other_line
from . import damage_type_other_line